/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MillType = IDL.Variant({
  'dal' : IDL.Null,
  'flour' : IDL.Null,
  'other' : IDL.Null,
  'rice' : IDL.Null,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'isDemo' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'millType' : MillType,
});

export const idlService = IDL.Service({
  'getCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getEnquiriesByTimestamp' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getEnquiry' : IDL.Func([IDL.Nat], [Enquiry], ['query']),
  'submitEnquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        MillType,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MillType = IDL.Variant({
    'dal' : IDL.Null,
    'flour' : IDL.Null,
    'other' : IDL.Null,
    'rice' : IDL.Null,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'isDemo' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'millType' : MillType,
  });
  
  return IDL.Service({
    'getCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getEnquiriesByTimestamp' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getEnquiry' : IDL.Func([IDL.Nat], [Enquiry], ['query']),
    'submitEnquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          MillType,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };