/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Enquiry {
    id: bigint;
    city: string;
    name: string;
    isDemo: boolean;
    email: string;
    message: string;
    timestamp: bigint;
    companyName: string;
    phone: string;
    millType: MillType;
}
export enum MillType {
    dal = "dal",
    flour = "flour",
    other = "other",
    rice = "rice"
}
export interface backendInterface {
    getCount(): Promise<bigint>;
    getEnquiries(): Promise<Array<Enquiry>>;
    getEnquiriesByTimestamp(): Promise<Array<Enquiry>>;
    getEnquiry(id: bigint): Promise<Enquiry>;
    submitEnquiry(name: string, companyName: string, city: string, phone: string, email: string, millType: MillType, message: string, isDemo: boolean): Promise<bigint>;
}
import type { Enquiry as _Enquiry, MillType as _MillType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCount();
            return result;
        }
    }
    async getEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnquiriesByTimestamp(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiriesByTimestamp();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiriesByTimestamp();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnquiry(arg0: bigint): Promise<Enquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiry(arg0);
                return from_candid_Enquiry_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiry(arg0);
            return from_candid_Enquiry_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitEnquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: MillType, arg6: string, arg7: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, arg4, to_candid_MillType_n6(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, arg4, to_candid_MillType_n6(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
}
function from_candid_Enquiry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enquiry): Enquiry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MillType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MillType): MillType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    city: string;
    name: string;
    isDemo: boolean;
    email: string;
    message: string;
    timestamp: bigint;
    companyName: string;
    phone: string;
    millType: _MillType;
}): {
    id: bigint;
    city: string;
    name: string;
    isDemo: boolean;
    email: string;
    message: string;
    timestamp: bigint;
    companyName: string;
    phone: string;
    millType: MillType;
} {
    return {
        id: value.id,
        city: value.city,
        name: value.name,
        isDemo: value.isDemo,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        companyName: value.companyName,
        phone: value.phone,
        millType: from_candid_MillType_n4(_uploadFile, _downloadFile, value.millType)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dal: null;
} | {
    flour: null;
} | {
    other: null;
} | {
    rice: null;
}): MillType {
    return "dal" in value ? MillType.dal : "flour" in value ? MillType.flour : "other" in value ? MillType.other : "rice" in value ? MillType.rice : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enquiry>): Array<Enquiry> {
    return value.map((x)=>from_candid_Enquiry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_MillType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MillType): _MillType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MillType): {
    dal: null;
} | {
    flour: null;
} | {
    other: null;
} | {
    rice: null;
} {
    return value == MillType.dal ? {
        dal: null
    } : value == MillType.flour ? {
        flour: null
    } : value == MillType.other ? {
        other: null
    } : value == MillType.rice ? {
        rice: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
